---
title: "Week 1 practice problems"
author: "Maureen Lahiff"
date: "March 3, 2019"
---

```{r set libraries and read in data }

# use the setwd() function to set up your working directory
# be sure you have the Excel dataset  wcgs_data.xlsx downloaded 
# into your working directory or into a folder you have created specifically for week 1

library(tidyverse)
library(readr)
library(readxl)

wcgs <- read_excel("wcgs_data.xlsx", col_names = TRUE)

```

```{r get numeric cholesterol variable}

wcgs$Chol0_new = as.numeric(wcgs$Chol0)

```

```{r create bmi}

# calculate Quetelet body mass index

wcgs$Heightincm0 <- wcgs$Height0*2.54
wcgs$Weightinkg0 <- wcgs$Weight0/2.2
wcgs$BMI0 <- wcgs$Weightinkg0/((wcgs$Heightincm0/100)^2)

```

```{r create binary smoker variable}

wcgs$Smoker0 <- 1
wcgs$Smoker0[wcgs$Ncigs0 == 0] <- 0
wcgs$Smoker0 <- factor(wcgs$Smoker0, labels= c("non-smoker", "smoker"))

```

```{r create high cholesterol variable}

anyNA(wcgs$Chol0_new)

wcgs$HighChol0 <- 1
wcgs$HighChol0[wcgs$Chol0_new < 240] <- 0
wcgs$HighChol0[is.na(wcgs$Chol0_new)] <- NA
wcgs$HighChol0 <- factor(wcgs$HighChol0, labels= c("Chol low", "Chol high"))

```

```{r write out a .csv file with new variables}

write_csv(wcgs, "wcgs_data_rev.csv", col_names = TRUE)

```

```{r  5 number summary and average and standard deviaton for cholesterol}

# this function handles the missing values gracefully

summary(wcgs$Chol0_new)

#  but these do not --try them to see what you get:

mean(wcgs$Chol0_new)
sd(wcgs$Chol0_new)

# here is what we need; na.rm says to remove, or ignore, missing values

mean(wcgs$Chol0_new, na.rm = TRUE)
sd(wcgs$Chol0_new, na.rm = TRUE)

# it is a good idea to add the argument that asks the calculations to ignore missing

wcgs %>% summarize(
    min = min(Chol0_new, na.rm = TRUE) ,
    q1 = sprintf("%0.2f", quantile(Chol0_new, na.rm = TRUE, 0.25))  ,
    median = sprintf("%0.2f", quantile(Chol0_new, na.rm = TRUE, 0.50)) ,
    q3 = sprintf("%0.2f", quantile(Chol0_new, na.rm = TRUE, 0.75)) ,
    max = max(Chol0_new, na.rm = TRUE)
)

wcgs %>% summarize(
    ave = sprintf("%0.2f", mean(Chol0_new, na.rm = TRUE) ) ,
    std_dev = sprintf("%0.2f",sd(Chol0_new, na.rm = TRUE) )
)

```

```{r histogram for Chol0 values}

ggplot(wcgs, aes(x = Chol0_new, y = ..density..)) +
  geom_histogram(binwidth = 10, color = "black", fill = "blue") +
        labs(   
          title = "WCGS cholesterol values at baseline", 
          subtitle = "n = 3154 men ages 39 to 59", 
          x = "cholesterol in mg/100 ml", y = "density" ) +
          scale_x_continuous(limits = c(100, 650)  , 
            breaks = c(100,200,300,400,500,600) ,
            labels = c(100,200,300,400,500,600) ) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))

```

```{r box plot for Chol0 values}

ggplot(wcgs, aes(y = Chol0_new) ) +
  geom_boxplot(width = 0.5) +
    scale_x_continuous(labels = NULL) +
    labs(y = "cholesterol in mg/100ml", x = "",      
         title = "WCGS cholesterol values at baseline", 
          subtitle = "n = 3154 men ages 39 to 59") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))

```

